import Link from 'next/link';

export default function ShareLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col bg-neutral-50">
      <header className="border-b border-neutral-200 bg-white">
        <div className="mx-auto flex h-14 w-full max-w-4xl items-center justify-between px-4">
          <Link
            href="/"
            className="text-base font-semibold tracking-tight text-neutral-900"
          >
            CarrierAudit
          </Link>
          <span className="text-xs text-neutral-500">Shared report</span>
        </div>
      </header>
      <main className="mx-auto w-full max-w-4xl flex-1 px-4 py-8">{children}</main>
      <footer className="border-t border-neutral-200 bg-white">
        <div className="mx-auto flex h-12 w-full max-w-4xl items-center justify-center px-4 text-xs text-neutral-500">
          <span>
            Generated by{' '}
            <Link href="/" className="text-neutral-900 hover:underline">
              CarrierAudit
            </Link>
          </span>
        </div>
      </footer>
    </div>
  );
}
