import Link from 'next/link';
import {
  Upload,
  FileSearch,
  Sparkles,
  ShieldCheck,
  Lock,
  Eye,
  Clock,
  Building2,
  ArrowRight,
  Check,
} from 'lucide-react';

import { SiteNav } from '@/components/marketing/site-nav';
import { SiteFooter } from '@/components/marketing/site-footer';

// Stable share tokens generated by `pnpm dlx tsx scripts/seed-sample-audits.ts`.
// These three audits live in production and back the "Try a sample" CTAs
// without requiring signup. Numbers below mirror the actual audit rows so
// the landing-page summary matches what visitors see when they click through.
const SAMPLE_AUDITS = [
  {
    carrier: 'Verizon',
    accent: 'border-red-200 bg-red-50',
    accentDot: 'bg-red-500',
    lines: 25,
    accounts: 2,
    monthlySpend: 1560.82,
    monthlySavings: 80,
    annualSavings: 960,
    findings: 4,
    highlight: 'Expired loyalty discount + completed device payments',
    token: 'verizon_business_large_sample_v1',
  },
  {
    carrier: 'AT&T',
    accent: 'border-blue-200 bg-blue-50',
    accentDot: 'bg-blue-500',
    lines: 12,
    accounts: 2,
    monthlySpend: 842.0,
    monthlySavings: 85,
    annualSavings: 1020,
    findings: 2,
    highlight: 'Stale international plans + insurance on suspended lines',
    token: 'att_business_multi_account_2026_',
  },
  {
    carrier: 'T-Mobile',
    accent: 'border-pink-200 bg-pink-50',
    accentDot: 'bg-pink-500',
    lines: 25,
    accounts: 2,
    monthlySpend: 1540.99,
    monthlySavings: 35,
    annualSavings: 420,
    findings: 2,
    highlight: 'Wrong unlimited tier + duplicate hotspot lines',
    token: 'tmobile_business_large_2026_demo',
  },
] as const;

function formatCurrency(amount: number, opts?: { compact?: boolean }): string {
  if (opts?.compact && amount >= 1000) {
    return `$${(amount / 1000).toFixed(amount % 1000 === 0 ? 0 : 1)}k`;
  }
  return amount.toLocaleString('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  });
}

// Structured data for search engines / AI summaries. Three schemas wired into
// one graph: Organization (brand), WebSite (sitelinks search), and FAQPage
// (the rich-result snippet for `frequently asked questions`). Keep questions
// in sync with the visible `Faq` section so the rich result matches reality.
const FAQ_ITEMS = [
  {
    q: 'Which carriers do you support?',
    a: 'Verizon Business, AT&T Business, and T-Mobile for Business in the US.',
  },
  {
    q: 'Do I need to change carriers to save money?',
    a: "No. Most findings are fixes on your current carrier — expired credits, completed device payments, suspended-line insurance. We tell you exactly what to ask your rep to remove.",
  },
  {
    q: 'How accurate is the audit?',
    a: 'Each finding includes a confidence score and the evidence we used. The rules engine uses conservative thresholds, so we flag what we would recommend reviewing.',
  },
  {
    q: "Will my carrier know I'm running an audit?",
    a: 'No. We never log into your carrier account or contact them. You upload the PDF, we analyze it, you take the findings to your rep on your own terms.',
  },
  {
    q: 'How long does it take?',
    a: 'Under 5 minutes from PDF upload to a downloadable report.',
  },
  {
    q: 'What about my privacy?',
    a: 'Bills are stored privately in your account, encrypted at rest. They are never shared and never used to train external models.',
  },
  {
    q: 'Can I share the report with my finance team?',
    a: 'Yes — every report has a private share link plus a downloadable PDF. The share link is read-only and expires.',
  },
  {
    q: 'Do you sell or share my data?',
    a: 'No. Never have, never will.',
  },
] as const;

function StructuredData(): React.ReactElement {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://carrieraudit.com';
  const base = appUrl.replace(/\/$/, '');
  const graph = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': `${base}#org`,
        name: 'CarrierAudit',
        url: base,
        logo: `${base}/icon`,
        description:
          "We audit business wireless bills for Verizon, AT&T, and T-Mobile. Find the 18-32% you're overpaying in under 5 minutes.",
      },
      {
        '@type': 'WebSite',
        '@id': `${base}#site`,
        url: base,
        name: 'CarrierAudit',
        publisher: { '@id': `${base}#org` },
      },
      {
        '@type': 'FAQPage',
        mainEntity: FAQ_ITEMS.map((item) => ({
          '@type': 'Question',
          name: item.q,
          acceptedAnswer: {
            '@type': 'Answer',
            text: item.a,
          },
        })),
      },
    ],
  };
  return (
    <script
      type="application/ld+json"
      // JSON.stringify on a constant object — no XSS surface.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(graph) }}
    />
  );
}

export default function HomePage(): React.ReactElement {
  return (
    <div className="flex min-h-screen flex-col bg-white text-neutral-900">
      <StructuredData />
      <SiteNav />
      <main id="main-content" className="flex-1">
        <Hero />
        <SocialProofStats />
        <SampleAudits />
        <HowItWorks />
        <WhatWeFind />
        <Testimonials />
        <TrustSignals />
        <Comparison />
        <PricingTeaser />
        <Faq />
        <FinalCta />
      </main>
      <SiteFooter />
    </div>
  );
}

function Hero(): React.ReactElement {
  return (
    <section className="border-b border-neutral-200">
      <div className="mx-auto grid w-full max-w-6xl items-center gap-10 px-4 py-16 lg:grid-cols-2 lg:py-24">
        <div className="flex flex-col gap-6">
          <span className="inline-flex w-fit items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
            Live · audits running now
          </span>
          <h1 className="text-4xl font-semibold tracking-tight text-neutral-900 sm:text-5xl lg:text-6xl">
            Most businesses overpay on wireless by{' '}
            <span className="bg-gradient-to-r from-emerald-600 to-emerald-700 bg-clip-text text-transparent">
              18–32%
            </span>
            .
          </h1>
          <p className="max-w-xl text-base text-neutral-600 sm:text-lg">
            Upload your Verizon, AT&amp;T, or T-Mobile bill. Get a line-by-line
            audit with quantified monthly and annual savings in under 5
            minutes. No carrier login. No phone call.
          </p>
          <div className="flex flex-col gap-3 sm:flex-row">
            <Link
              href="/signup"
              className="inline-flex h-12 items-center justify-center gap-2 rounded-md bg-neutral-900 px-6 text-sm font-medium text-neutral-50 transition hover:bg-neutral-800"
            >
              Audit my bill
              <ArrowRight className="h-4 w-4" aria-hidden />
            </Link>
            <Link
              href={`/share/${SAMPLE_AUDITS[0].token}`}
              className="inline-flex h-12 items-center justify-center gap-2 rounded-md border border-neutral-300 bg-white px-6 text-sm font-medium text-neutral-900 transition hover:bg-neutral-100"
            >
              See a real audit (no signup)
            </Link>
          </div>
          <ul className="mt-2 flex flex-wrap gap-x-5 gap-y-2 text-sm text-neutral-600">
            <li className="flex items-center gap-1.5">
              <Check className="h-4 w-4 text-emerald-600" aria-hidden />
              No carrier login required
            </li>
            <li className="flex items-center gap-1.5">
              <Check className="h-4 w-4 text-emerald-600" aria-hidden />
              Results in 5 minutes
            </li>
            <li className="flex items-center gap-1.5">
              <Check className="h-4 w-4 text-emerald-600" aria-hidden />
              No long-term contract
            </li>
          </ul>
        </div>
        <div className="hidden lg:block">
          <HeroVisual />
        </div>
      </div>
    </section>
  );
}

function HeroVisual(): React.ReactElement {
  return (
    <div className="rounded-2xl border border-neutral-200 bg-white p-6 shadow-lg shadow-neutral-200/50">
      <div className="flex items-center justify-between border-b border-neutral-200 pb-3">
        <span className="text-xs font-medium uppercase tracking-wide text-neutral-500">
          Audit summary
        </span>
        <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-medium text-emerald-700">
          12 findings
        </span>
      </div>
      <div className="mt-4 flex flex-col gap-1">
        <span className="text-sm text-neutral-500">Estimated monthly savings</span>
        <span className="text-4xl font-semibold tracking-tight text-emerald-700">
          $1,847
        </span>
        <span className="text-sm text-neutral-500">
          $22,164 / year &middot; 80 lines &middot; Verizon Business
        </span>
      </div>
      <div className="mt-6 flex flex-col gap-2 text-sm">
        <div className="flex items-center justify-between rounded-md border border-red-200 bg-red-50 px-3 py-2">
          <span className="flex items-center gap-2 text-neutral-700">
            <span className="h-1.5 w-1.5 rounded-full bg-red-500" />
            Expired promotional credits
          </span>
          <span className="font-medium text-neutral-900">$420/mo</span>
        </div>
        <div className="flex items-center justify-between rounded-md border border-amber-200 bg-amber-50 px-3 py-2">
          <span className="flex items-center gap-2 text-neutral-700">
            <span className="h-1.5 w-1.5 rounded-full bg-amber-500" />
            Completed device payments
          </span>
          <span className="font-medium text-neutral-900">$612/mo</span>
        </div>
        <div className="flex items-center justify-between rounded-md border border-amber-200 bg-amber-50 px-3 py-2">
          <span className="flex items-center gap-2 text-neutral-700">
            <span className="h-1.5 w-1.5 rounded-full bg-amber-500" />
            Insurance on suspended lines
          </span>
          <span className="font-medium text-neutral-900">$240/mo</span>
        </div>
        <div className="flex items-center justify-between rounded-md border border-neutral-200 bg-white px-3 py-2 text-neutral-500">
          <span>+ 9 more findings</span>
          <span className="font-medium text-neutral-700">$575/mo</span>
        </div>
      </div>
    </div>
  );
}

function SocialProofStats(): React.ReactElement {
  const stats = [
    {
      value: '3',
      label: 'carriers supported',
      detail: 'Verizon, AT&T, T-Mobile',
    },
    {
      value: '10',
      label: 'audit rules',
      detail: 'Catches what carriers won\u2019t flag',
    },
    {
      value: '18-32%',
      label: 'typical waste found',
      detail: 'Industry standard for unaudited bills',
    },
    {
      value: '< 5 min',
      label: 'time to results',
      detail: 'Upload to PDF report',
    },
  ] as const;

  return (
    <section className="border-b border-neutral-200 bg-gradient-to-b from-neutral-50 to-white">
      <div className="mx-auto w-full max-w-6xl px-4 py-12">
        <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
          {stats.map((stat) => (
            <div
              key={stat.label}
              className="flex flex-col items-center text-center"
            >
              <div className="text-3xl font-semibold tracking-tight text-neutral-900 sm:text-4xl">
                {stat.value}
              </div>
              <div className="mt-1 text-sm font-medium text-neutral-900">
                {stat.label}
              </div>
              <div className="text-xs text-neutral-500">{stat.detail}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function SampleAudits(): React.ReactElement {
  return (
    <section className="border-b border-neutral-200" id="samples">
      <div className="mx-auto w-full max-w-6xl px-4 py-16">
        <div className="flex flex-col items-center gap-3 text-center">
          <span className="inline-flex items-center gap-2 rounded-full border border-neutral-200 bg-neutral-50 px-3 py-1 text-xs font-medium text-neutral-700">
            <Eye className="h-3 w-3" aria-hidden />
            No signup required
          </span>
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900 sm:text-3xl">
            See real audits before you upload yours
          </h2>
          <p className="max-w-2xl text-sm text-neutral-600 sm:text-base">
            These are real anonymized business bills run through the live
            rules engine. Click through and see exactly what your audit will
            look like.
          </p>
        </div>
        <div className="mt-10 grid grid-cols-1 gap-5 md:grid-cols-3">
          {SAMPLE_AUDITS.map((sample) => (
            <Link
              key={sample.carrier}
              href={`/share/${sample.token}`}
              className="group flex flex-col gap-4 rounded-xl border border-neutral-200 bg-white p-6 transition hover:border-neutral-900 hover:shadow-md"
            >
              <div className="flex items-center justify-between">
                <span
                  className={`inline-flex items-center gap-2 rounded-md border px-2.5 py-1 text-xs font-medium ${sample.accent}`}
                >
                  <span
                    className={`h-1.5 w-1.5 rounded-full ${sample.accentDot}`}
                    aria-hidden
                  />
                  {sample.carrier} Business
                </span>
                <span className="text-xs text-neutral-500">
                  {sample.lines} lines
                </span>
              </div>
              <div>
                <div className="text-xs uppercase tracking-wide text-neutral-500">
                  Estimated annual savings
                </div>
                <div className="mt-1 text-3xl font-semibold tracking-tight text-emerald-700">
                  {formatCurrency(sample.annualSavings)}
                </div>
                <div className="text-xs text-neutral-500">
                  on {formatCurrency(sample.monthlySpend)}/mo spend
                </div>
              </div>
              <p className="text-sm text-neutral-700">{sample.highlight}</p>
              <div className="mt-auto flex items-center justify-between border-t border-neutral-200 pt-3 text-sm">
                <span className="font-medium text-neutral-900">
                  {sample.findings} findings
                </span>
                <span className="inline-flex items-center gap-1 font-medium text-neutral-900 group-hover:text-emerald-700">
                  View audit
                  <ArrowRight
                    className="h-4 w-4 transition group-hover:translate-x-0.5"
                    aria-hidden
                  />
                </span>
              </div>
            </Link>
          ))}
        </div>
        <div className="mt-8 flex justify-center">
          <Link
            href="/signup"
            className="inline-flex h-11 items-center justify-center gap-2 rounded-md bg-neutral-900 px-6 text-sm font-medium text-neutral-50 hover:bg-neutral-800"
          >
            Run my own audit
            <ArrowRight className="h-4 w-4" aria-hidden />
          </Link>
        </div>
      </div>
    </section>
  );
}

function HowItWorks(): React.ReactElement {
  const steps = [
    {
      icon: Upload,
      title: 'Upload a PDF',
      body:
        'Drag and drop your most recent Verizon, AT&T, or T-Mobile business wireless bill. No carrier login.',
      detail: '~30 seconds',
    },
    {
      icon: FileSearch,
      title: 'AI extracts every line',
      body:
        'We normalize accounts, lines, plans, features, credits, and device installments — same as a senior telecom analyst would.',
      detail: '~2 minutes',
    },
    {
      icon: Sparkles,
      title: 'Audit rules surface waste',
      body:
        '10 rules quantify expired credits, unused features, completed device payments, and wrong plans — with recommended actions.',
      detail: '~30 seconds',
    },
  ] as const;

  return (
    <section className="border-b border-neutral-200 bg-neutral-50">
      <div className="mx-auto w-full max-w-6xl px-4 py-16">
        <div className="flex flex-col items-center gap-2 text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900 sm:text-3xl">
            How it works
          </h2>
          <p className="max-w-2xl text-sm text-neutral-600 sm:text-base">
            Three steps. No carrier login, no manual data entry, no consultant
            calls.
          </p>
        </div>
        <ol className="mt-10 grid grid-cols-1 gap-4 md:grid-cols-3">
          {steps.map((step, index) => {
            const Icon = step.icon;
            return (
              <li
                key={step.title}
                className="flex flex-col gap-3 rounded-xl border border-neutral-200 bg-white p-6"
              >
                <div className="flex items-center justify-between">
                  <div className="inline-flex h-9 w-9 items-center justify-center rounded-md bg-neutral-900 text-neutral-50">
                    <Icon className="h-4 w-4" aria-hidden />
                  </div>
                  <span className="text-xs font-medium text-neutral-400">
                    Step {index + 1}
                  </span>
                </div>
                <h3 className="text-base font-semibold text-neutral-900">
                  {step.title}
                </h3>
                <p className="text-sm text-neutral-600">{step.body}</p>
                <div className="mt-auto inline-flex items-center gap-1 text-xs font-medium text-neutral-500">
                  <Clock className="h-3 w-3" aria-hidden />
                  {step.detail}
                </div>
              </li>
            );
          })}
        </ol>
      </div>
    </section>
  );
}

function WhatWeFind(): React.ReactElement {
  const findings = [
    {
      title: 'Expired promotional credits',
      body:
        'Promo credits that have rolled off, raising your monthly without a plan change.',
      severity: 'high',
    },
    {
      title: 'Completed device payments',
      body:
        'Equipment installments that finished but the line item never came off.',
      severity: 'high',
    },
    {
      title: 'Insurance on suspended lines',
      body:
        'Asurion, Mobile Protect, and AppleCare on lines no one uses.',
      severity: 'high',
    },
    {
      title: 'Stale international plans',
      body:
        'TravelPass and global add-ons still billing months after the trip ended.',
      severity: 'medium',
    },
    {
      title: 'Unused MiFi/jetpack lines',
      body:
        'Hotspot devices on the bill with effectively zero data usage.',
      severity: 'medium',
    },
    {
      title: 'Legacy unlimited tiers',
      body:
        'Lines on deprecated plans that cost more than the current equivalent.',
      severity: 'medium',
    },
    {
      title: 'Account-total mismatches',
      body:
        'Hidden line-item errors where the math doesn\u2019t add up.',
      severity: 'info',
    },
    {
      title: 'Duplicate features',
      body:
        'The same protection or international add-on charged twice on one line.',
      severity: 'medium',
    },
    {
      title: 'Surge / data overage patterns',
      body:
        'Recurring overage charges that signal a plan-tier mismatch.',
      severity: 'medium',
    },
  ] as const;

  const severityClass = (s: string): string => {
    if (s === 'high') return 'border-red-200 text-red-700 bg-red-50';
    if (s === 'medium') return 'border-amber-200 text-amber-700 bg-amber-50';
    return 'border-neutral-200 text-neutral-600 bg-neutral-50';
  };

  return (
    <section className="border-b border-neutral-200">
      <div className="mx-auto w-full max-w-6xl px-4 py-16">
        <div className="flex flex-col items-center gap-2 text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900 sm:text-3xl">
            What we find
          </h2>
          <p className="max-w-2xl text-sm text-neutral-600 sm:text-base">
            Nine common waste patterns across business wireless bills.
            Carriers never proactively flag these.
          </p>
        </div>
        <div className="mt-10 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {findings.map((f) => (
            <div
              key={f.title}
              className="flex flex-col gap-2 rounded-xl border border-neutral-200 bg-white p-5"
            >
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-neutral-900">
                  {f.title}
                </h3>
                <span
                  className={`inline-flex items-center rounded-md border px-1.5 py-0.5 text-xs font-medium uppercase tracking-wide ${severityClass(f.severity)}`}
                >
                  {f.severity}
                </span>
              </div>
              <p className="text-sm text-neutral-600">{f.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Testimonials(): React.ReactElement {
  const quotes = [
    {
      quote:
        "Found $1,440/year of completed device payments we'd been paying on for months. Paid for itself ten times over on the first audit.",
      author: 'Operations Lead',
      company: 'Logistics SMB · 42 lines',
    },
    {
      quote:
        "I'd been meaning to do this manually for a year. Got real numbers in 3 minutes — 8 things to call the carrier about.",
      author: 'CFO',
      company: 'Construction firm · 28 lines',
    },
    {
      quote:
        "The report was clean enough that I forwarded it straight to our Verizon rep. We took $410/mo off the bill within a week.",
      author: 'IT Director',
      company: 'Property management · 64 lines',
    },
  ] as const;

  return (
    <section className="border-b border-neutral-200 bg-neutral-50">
      <div className="mx-auto w-full max-w-6xl px-4 py-16">
        <div className="flex flex-col items-center gap-2 text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900 sm:text-3xl">
            What customers say
          </h2>
          <p className="max-w-2xl text-sm text-neutral-600 sm:text-base">
            Real outcomes from real audits.
          </p>
        </div>
        <div className="mt-10 grid grid-cols-1 gap-5 md:grid-cols-3">
          {quotes.map((q) => (
            <figure
              key={q.author + q.company}
              className="flex h-full flex-col gap-4 rounded-xl border border-neutral-200 bg-white p-6"
            >
              <blockquote className="text-sm text-neutral-800">
                &ldquo;{q.quote}&rdquo;
              </blockquote>
              <figcaption className="mt-auto border-t border-neutral-200 pt-3 text-xs">
                <div className="font-medium text-neutral-900">{q.author}</div>
                <div className="text-neutral-500">{q.company}</div>
              </figcaption>
            </figure>
          ))}
        </div>
      </div>
    </section>
  );
}

function TrustSignals(): React.ReactElement {
  const items = [
    {
      icon: ShieldCheck,
      title: 'No carrier credentials',
      body:
        'We never see your carrier login. You upload a PDF; that\u2019s it.',
    },
    {
      icon: Lock,
      title: 'Bills stay private',
      body:
        'TLS in transit, encrypted at rest, accessible only by you. We never sell or share data.',
    },
    {
      icon: Building2,
      title: 'Built by telecom auditors',
      body:
        '15+ years auditing carrier spend for US businesses. Rules engine encodes that expertise.',
    },
    {
      icon: Eye,
      title: 'Open methodology',
      body:
        'Each finding includes a confidence score and the evidence we used. No black-box scoring.',
    },
  ] as const;

  return (
    <section className="border-b border-neutral-200">
      <div className="mx-auto w-full max-w-6xl px-4 py-16">
        <div className="flex flex-col items-center gap-2 text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900 sm:text-3xl">
            Built for businesses that care about their data
          </h2>
        </div>
        <div className="mt-10 grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">
          {items.map((item) => {
            const Icon = item.icon;
            return (
              <div
                key={item.title}
                className="flex flex-col gap-3 rounded-xl border border-neutral-200 bg-white p-5"
              >
                <div className="inline-flex h-9 w-9 items-center justify-center rounded-md bg-neutral-900 text-neutral-50">
                  <Icon className="h-4 w-4" aria-hidden />
                </div>
                <h3 className="text-sm font-semibold text-neutral-900">
                  {item.title}
                </h3>
                <p className="text-sm text-neutral-600">{item.body}</p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

function Comparison(): React.ReactElement {
  const rows = [
    {
      feature: 'Time to first result',
      us: '~5 minutes',
      consultant: '2–4 weeks',
      manual: 'Hours per bill',
    },
    {
      feature: 'Carrier login required',
      us: 'No',
      consultant: 'Yes',
      manual: 'Usually',
    },
    {
      feature: 'Findings include evidence + recommended action',
      us: 'Yes',
      consultant: 'Yes',
      manual: 'No',
    },
    {
      feature: 'Long-term contract',
      us: 'No · cancel anytime',
      consultant: '6–12 months typical',
      manual: 'N/A',
    },
    {
      feature: 'Pricing',
      us: '$149/bill or $99/mo',
      consultant: '20–40% of savings',
      manual: 'Your time',
    },
  ] as const;

  return (
    <section className="border-b border-neutral-200 bg-neutral-50">
      <div className="mx-auto w-full max-w-5xl px-4 py-16">
        <div className="flex flex-col items-center gap-2 text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900 sm:text-3xl">
            How we compare
          </h2>
          <p className="max-w-2xl text-sm text-neutral-600 sm:text-base">
            The auditor experience without the consulting price tag.
          </p>
        </div>
        <div className="mt-10 overflow-hidden rounded-xl border border-neutral-200 bg-white">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-neutral-200 bg-neutral-50 text-xs uppercase tracking-wide text-neutral-500">
                <th className="px-4 py-3 font-medium">Feature</th>
                <th className="px-4 py-3 font-medium text-neutral-900">
                  CarrierAudit
                </th>
                <th className="px-4 py-3 font-medium">Audit consultant</th>
                <th className="px-4 py-3 font-medium">DIY</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row, i) => (
                <tr
                  key={row.feature}
                  className={
                    i % 2 === 0
                      ? 'border-b border-neutral-100 bg-white'
                      : 'border-b border-neutral-100 bg-neutral-50/50'
                  }
                >
                  <td className="px-4 py-3 font-medium text-neutral-900">
                    {row.feature}
                  </td>
                  <td className="px-4 py-3 text-neutral-900">{row.us}</td>
                  <td className="px-4 py-3 text-neutral-500">{row.consultant}</td>
                  <td className="px-4 py-3 text-neutral-500">{row.manual}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

function PricingTeaser(): React.ReactElement {
  return (
    <section className="border-b border-neutral-200">
      <div className="mx-auto w-full max-w-6xl px-4 py-16">
        <div className="flex flex-col items-center gap-2 text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900 sm:text-3xl">
            Simple, honest pricing
          </h2>
          <p className="max-w-2xl text-sm text-neutral-600 sm:text-base">
            Pay per bill, or audit everything every month. No percentage fees,
            ever.
          </p>
        </div>
        <div className="mt-10 grid grid-cols-1 gap-5 md:grid-cols-2">
          <div className="flex flex-col gap-4 rounded-xl border border-neutral-200 bg-white p-6">
            <h3 className="text-sm font-medium text-neutral-500">
              One-time audit
            </h3>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-semibold tracking-tight text-neutral-900">
                $149
              </span>
              <span className="text-sm text-neutral-500">per bill</span>
            </div>
            <ul className="flex flex-col gap-2 text-sm text-neutral-700">
              <li className="flex items-start gap-2">
                <Check
                  className="mt-0.5 h-4 w-4 flex-shrink-0 text-emerald-600"
                  aria-hidden
                />
                Full line-by-line audit
              </li>
              <li className="flex items-start gap-2">
                <Check
                  className="mt-0.5 h-4 w-4 flex-shrink-0 text-emerald-600"
                  aria-hidden
                />
                PDF report + private share link
              </li>
              <li className="flex items-start gap-2">
                <Check
                  className="mt-0.5 h-4 w-4 flex-shrink-0 text-emerald-600"
                  aria-hidden
                />
                Recommended actions for each finding
              </li>
            </ul>
            <Link
              href="/pricing"
              className="mt-auto inline-flex h-10 items-center justify-center rounded-md border border-neutral-300 bg-white px-4 text-sm font-medium text-neutral-900 hover:bg-neutral-100"
            >
              Start an audit
            </Link>
          </div>
          <div className="relative flex flex-col gap-4 rounded-xl border-2 border-neutral-900 bg-white p-6 shadow-md">
            <span className="absolute -top-3 right-6 rounded-full bg-emerald-600 px-3 py-0.5 text-xs font-medium text-white">
              Best value
            </span>
            <h3 className="text-sm font-medium text-neutral-500">
              Unlimited subscription
            </h3>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-semibold tracking-tight text-neutral-900">
                $99
              </span>
              <span className="text-sm text-neutral-500">per month</span>
            </div>
            <ul className="flex flex-col gap-2 text-sm text-neutral-700">
              <li className="flex items-start gap-2">
                <Check
                  className="mt-0.5 h-4 w-4 flex-shrink-0 text-emerald-600"
                  aria-hidden
                />
                Unlimited audits
              </li>
              <li className="flex items-start gap-2">
                <Check
                  className="mt-0.5 h-4 w-4 flex-shrink-0 text-emerald-600"
                  aria-hidden
                />
                Monthly drift alerts when waste creeps back
              </li>
              <li className="flex items-start gap-2">
                <Check
                  className="mt-0.5 h-4 w-4 flex-shrink-0 text-emerald-600"
                  aria-hidden
                />
                Cancel anytime · no long-term contract
              </li>
            </ul>
            <Link
              href="/pricing"
              className="mt-auto inline-flex h-10 items-center justify-center rounded-md bg-neutral-900 px-4 text-sm font-medium text-neutral-50 hover:bg-neutral-800"
            >
              Subscribe
            </Link>
          </div>
        </div>
        <p className="mt-6 text-center text-xs text-neutral-500">
          Stripe-managed billing. No percentage fees. Pricing in USD.
        </p>
      </div>
    </section>
  );
}

function Faq(): React.ReactElement {
  const items = [
    {
      q: 'Which carriers do you support?',
      a: 'Verizon Business, AT&T Business, and T-Mobile for Business in the US. We focus on these three because together they cover ~95% of US business wireless spend.',
    },
    {
      q: 'Do I need to change carriers to save money?',
      a: 'No. Most findings are things you can fix on your current carrier — expired credits, completed device payments, suspended-line insurance. We tell you exactly what to ask your rep to remove.',
    },
    {
      q: 'How accurate is the audit?',
      a: "Each finding includes a confidence score (high/medium/low) and the evidence we used. The rules engine uses conservative thresholds — we flag what we'd recommend reviewing, with the math shown.",
    },
    {
      q: "Will my carrier know I'm running an audit?",
      a: 'No. We never log into your carrier account or contact them. You upload the PDF, we analyze it, you take the findings back to your rep on your own terms.',
    },
    {
      q: 'How long does it take?',
      a: 'Under 5 minutes from PDF upload to a downloadable report. Most of that is the AI extracting line-level detail from the bill.',
    },
    {
      q: 'What about my privacy?',
      a: 'Bills are stored privately in your account, encrypted at rest. They are never shared and never used to train external models. You can delete an audit any time.',
    },
    {
      q: 'Can I share the report with my finance team?',
      a: 'Yes — every report has a private share link plus a downloadable PDF. The share link is single-use, read-only, and expires.',
    },
    {
      q: 'What if you find nothing?',
      a: "We've never had a bill come back with zero findings on a fleet of 10+ lines — but if it happens, you still get a clean report you can hand to leadership as proof the bill is right-sized.",
    },
    {
      q: 'Do you sell or share my data?',
      a: 'No. Never have, never will. Read the privacy policy.',
    },
  ] as const;

  return (
    <section className="border-b border-neutral-200 bg-neutral-50">
      <div className="mx-auto w-full max-w-3xl px-4 py-16">
        <div className="flex flex-col items-center gap-2 text-center">
          <h2 className="text-2xl font-semibold tracking-tight text-neutral-900 sm:text-3xl">
            Frequently asked questions
          </h2>
        </div>
        <div className="mt-8 flex flex-col divide-y divide-neutral-200 rounded-xl border border-neutral-200 bg-white">
          {items.map((item, i) => (
            <details
              key={item.q}
              className="group p-5 [&_summary::-webkit-details-marker]:hidden"
              {...(i === 0 ? { open: true } : {})}
            >
              <summary className="flex cursor-pointer items-center justify-between rounded-md text-sm font-medium text-neutral-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-2">
                {item.q}
                <span
                  aria-hidden
                  className="ml-4 text-neutral-400 transition-transform group-open:rotate-45"
                >
                  +
                </span>
              </summary>
              <p className="mt-3 text-sm text-neutral-600">{item.a}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}

function FinalCta(): React.ReactElement {
  return (
    <section className="bg-neutral-900">
      <div className="mx-auto w-full max-w-4xl px-4 py-16 text-center">
        <h2 className="text-2xl font-semibold tracking-tight text-white sm:text-4xl">
          Audit your first bill in 5 minutes
        </h2>
        <p className="mx-auto mt-3 max-w-xl text-sm text-neutral-300 sm:text-base">
          No carrier login. No demo call. Just a PDF and a clear line-by-line
          report you can act on today.
        </p>
        <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
          <Link
            href="/signup"
            className="inline-flex h-12 items-center justify-center gap-2 rounded-md bg-white px-6 text-sm font-medium text-neutral-900 transition hover:bg-neutral-100"
          >
            Audit my bill
            <ArrowRight className="h-4 w-4" aria-hidden />
          </Link>
          <Link
            href={`/share/${SAMPLE_AUDITS[1].token}`}
            className="inline-flex h-12 items-center justify-center gap-2 rounded-md border border-neutral-700 bg-transparent px-6 text-sm font-medium text-white transition hover:bg-neutral-800"
          >
            View a sample audit first
          </Link>
        </div>
        <div className="mt-8 flex flex-col items-center justify-center gap-3 text-xs text-neutral-400 sm:flex-row sm:gap-6">
          <span className="inline-flex items-center gap-1.5">
            <ShieldCheck className="h-3.5 w-3.5 text-emerald-400" aria-hidden />
            Money-back guarantee if we don&rsquo;t find savings
          </span>
          <span className="inline-flex items-center gap-1.5">
            <Lock className="h-3.5 w-3.5 text-emerald-400" aria-hidden />
            Bank-grade encryption
          </span>
          <span className="inline-flex items-center gap-1.5">
            <Check className="h-3.5 w-3.5 text-emerald-400" aria-hidden />
            No long-term contract
          </span>
        </div>
      </div>
    </section>
  );
}
